local t = require("tests.harness")
local Config = require("imhex.config")

t.testcase("config: defaults present", function()
  Config.setup(nil)
  local cfg = Config.get()
  t.assert_eq(type(cfg), "table")
  t.assert_eq(type(cfg.ui), "table")
  t.assert_eq(cfg.ui.bytes_per_row, 16)
  t.assert_true(cfg.ui.show_ascii)
  t.assert_true(cfg.ui.show_hex)
  t.assert_true(cfg.ui.show_format)
  t.assert_eq(type(cfg.decode), "table")
  t.assert_eq(type(cfg.decode.prefer), "table")
  t.assert_eq(cfg.decode.prefer[1], "lua51")
end)

t.testcase("config: override merges shallow tables", function()
  Config.setup({ ui = { bytes_per_row = 8, show_ascii = false } })
  local cfg = Config.get()
  t.assert_eq(cfg.ui.bytes_per_row, 8)
  t.assert_eq(cfg.ui.show_ascii, false)
  t.assert_true(cfg.ui.show_hex)
  t.assert_true(cfg.ui.show_format)
end)

t.testcase("config: override nested sections", function()
  Config.setup({ decode = { prefer = { "foo", "bar" } } })
  local cfg = Config.get()
  t.assert_eq(cfg.decode.prefer[1], "foo")
  t.assert_eq(cfg.decode.prefer[2], "bar")
end)

